### ISSUE TITLE
SDK Crashing when the custom field scope is empty

### ISSUE THREAD

**Issue by vcidst** [verloop/android-sdk#13]
According to the docs, custom field can be set with the following command,

```
config.putCustomField("Test Field", "Test Value");
```

However this crashes the SDK
![](https://i.imgur.com/CUpgLKu.png)

When the scope is also passed, the crash doesn't happen,
```
config.putCustomField("Test Field", "Test Value", scope.ROOM);
```

**Comment by ravipetlur** [comment]
Fixed in the latest release.
