### ISSUE TITLE
Verloop android sdk 1.1.11 crashing

### ISSUE THREAD

**Issue by Anush01** [verloop/android-sdk#24]
FATAL EXCEPTION: main
                                                                                                    Process: , PID: 14489
                                                                                                    java.lang.IllegalArgumentException: No enum constant
                                                                                                    io.verloop.sdk.enum.Position.null
                                                                                                    	at java.lang.Enum.valueOf(Enum.java:259)
                                                                                                    	at io.verloop.sdk.enum.Position.valueOf(Unknown Source:2)
                                                                                                    	at
                                                                                                    io.verloop.sdk.ui.VerloopActivity.updateClientInfo(VerloopActivity.kt:164)
                                                                                                    	at
                                                                                                    io.verloop.sdk.ui.VerloopActivity.useDefaultHeader$lambda-1(VerloopActivity.kt:224)

**Comment by ravipetlur** [comment]
Can you share the android version you are trying this on?

**Comment by Anush01** [comment]
Android 14. I was using emulator that's bundled with Android studio.

**Comment by ravipetlur** [comment]
Tried this with android 13 and 14 and did not see any issues per say. Can you send out an email with details of the issue (how the integration is done) to support@verloop.io and we should be able to help.
