### ISSUE TITLE
Subscriber already registered

### ISSUE THREAD

**Issue by ShiveshM04** [verloop/android-sdk#4]
After minimizing the app, it is giving error.
   org.greenrobot.eventbus.EventBusException: Subscriber class io.verloop.sdk.VerloopActivity already registered to event class io.verloop.sdk.ClientInfoEvent

**Comment by raghav39** [comment]
Update to the newer version of SDK `1.0.7`

**Comment by ShiveshM04** [comment]
Thanks :-) 👍
